layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(RGBA8) uniform image3D u_voxel;

/* this shader sets the opacity to 1.0 for all voxels that have been written to
 * during the voxelization stage */
void main() {
	ivec3 coords = ivec3(gl_GlobalInvocationID);

	vec4 color = imageLoad(u_voxel, ivec3(coords));
	color.a = (color.a == 0.0) ? 0.0 : 1.0;
	imageStore(u_voxel, ivec3(coords), color);
}
